import React from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute } from '@react-navigation/native';
import { useTheme } from '../../contexts/ThemeContext';
import theme from '../../constants/theme';

export const ProfessionalDetailsScreen: React.FC = () => {
  const navigation = useNavigation<any>();
  const route = useRoute<any>();
  const { colors } = useTheme();
  const professional = route.params.professional;
  const open = (url?: string | null) => { if (!url) return; void Linking.openURL(url.startsWith('http') ? url : 'https://' + url); };
  const call = (phone?: string | null) => { if (phone) void Linking.openURL('tel:' + phone.replace(/\s/g, '')); };
  const whatsapp = (phone?: string | null) => { if (phone) void Linking.openURL('https://wa.me/' + phone.replace(/[^\d]/g, '')); };
  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.surface }]}><View style={styles.header}>
      <TouchableOpacity style={[styles.back, { backgroundColor: colors.surfaceContainer }]} onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={24} color={colors.onSurface} /></TouchableOpacity>
      <Text style={[styles.headerTitle, { color: colors.onSurface }]}>Professional profile</Text>
    </View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={[styles.hero, { backgroundColor: colors.surfaceContainer }]}><View style={[styles.avatar, { backgroundColor: colors.primary + '15' }]}><Ionicons name="person" size={34} color={colors.primary} /></View>
        <Text style={[styles.name, { color: colors.onSurface }]}>{professional.display_name || professional.name}</Text>
        <Text style={[styles.headline, { color: colors.primary }]}>{professional.headline || (professional.role || '').replaceAll('_', ' ')}</Text>
        {professional.verification_status === 'verified' && <View style={[styles.verified, { backgroundColor: colors.primary + '15' }]}><Ionicons name="checkmark-circle" size={15} color={colors.primary} /><Text style={[styles.verifiedText, { color: colors.primary }]}>Verified My Rights professional</Text></View>}
      </View>
      {professional.bio ? <Section title="About" colors={colors}><Text style={[styles.body, { color: colors.onSurfaceVariant }]}>{professional.bio}</Text></Section> : null}
      <Section title="Practice" colors={colors}><Info label="Practice areas" value={(professional.practice_areas || []).join(' • ')} colors={colors} /><Info label="Service areas" value={(professional.service_areas || []).join(' • ')} colors={colors} /><Info label="Languages" value={(professional.languages || []).join(' • ')} colors={colors} /><Info label="Experience" value={professional.years_experience != null ? professional.years_experience + ' years' : ''} colors={colors} /><Info label="Availability" value={professional.availability || ''} colors={colors} /><Info label="Fee band" value={professional.fee_band || ''} colors={colors} /></Section>
      {(professional.education?.length || professional.experience?.length || professional.certifications?.length || professional.skills?.length) ? <Section title="Professional background" colors={colors}>{professional.education?.length ? <List label="Education" values={professional.education} colors={colors} /> : null}{professional.experience?.length ? <List label="Experience" values={professional.experience} colors={colors} /> : null}{professional.certifications?.length ? <List label="Certifications" values={professional.certifications} colors={colors} /> : null}{professional.skills?.length ? <List label="Skills" values={professional.skills} colors={colors} /> : null}</Section> : null}
      {(professional.bar_admission_number || professional.bar_association || professional.nba_branch || professional.year_of_call || professional.jurisdiction) ? <Section title="Professional credentials" colors={colors}><Info label="Supreme Court Number" value={professional.bar_admission_number || ''} colors={colors} /><Info label="Bar association" value={professional.bar_association || ''} colors={colors} /><Info label="NBA branch" value={professional.nba_branch || ''} colors={colors} /><Info label="Year of call" value={professional.year_of_call ? String(professional.year_of_call) : ''} colors={colors} /><Info label="Jurisdiction" value={professional.jurisdiction || ''} colors={colors} /></Section> : null}
      <Section title="Contact" colors={colors}><View style={styles.contactGrid}>{professional.public_phone ? <Contact icon="call-outline" label="Call" onPress={() => call(professional.public_phone)} colors={colors} /> : null}{professional.whatsapp ? <Contact icon="logo-whatsapp" label="WhatsApp" onPress={() => whatsapp(professional.whatsapp)} colors={colors} /> : null}{professional.public_email ? <Contact icon="mail-outline" label="Email" onPress={() => void Linking.openURL('mailto:' + professional.public_email)} colors={colors} /> : null}{professional.instagram ? <Contact icon="logo-instagram" label="Instagram" onPress={() => open(professional.instagram)} colors={colors} /> : null}{professional.linkedin ? <Contact icon="logo-linkedin" label="LinkedIn" onPress={() => open(professional.linkedin)} colors={colors} /> : null}{professional.website ? <Contact icon="globe-outline" label="Website" onPress={() => open(professional.website)} colors={colors} /> : null}</View></Section>
      {professional.firms?.length ? <Section title="Firm / organisation" colors={colors}>{professional.firms.map((firm: any) => <View key={firm.id} style={[styles.firmRow, { backgroundColor: colors.surfaceContainer }]}><Ionicons name="business-outline" size={20} color={colors.primary} /><View style={styles.firmText}><Text style={[styles.firmName, { color: colors.onSurface }]}>{firm.name}</Text><Text style={[styles.body, { color: colors.onSurfaceVariant }]}>{firm.member_role || 'Member'}{firm.location ? ' • ' + firm.location : ''}</Text></View></View>)}</Section> : null}
      <TouchableOpacity style={[styles.enquiry, { backgroundColor: colors.primary }]} onPress={() => navigation.navigate('ProfessionalEnquiry', { professionalId: professional.id, professionalName: professional.display_name || professional.name, practiceArea: professional.practice_areas?.[0] })}><Ionicons name="chatbubble-ellipses-outline" size={20} color={colors.onPrimary} /><Text style={[styles.enquiryText, { color: colors.onPrimary }]}>Send legal enquiry</Text></TouchableOpacity>
    </ScrollView></SafeAreaView>
  );
};

function Section({ title, colors, children }: any) { return <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.onSurface }]}>{title}</Text><View style={[styles.card, { backgroundColor: colors.surfaceContainer }]}>{children}</View></View>; }
function Info({ label, value, colors }: any) { return value ? <View style={styles.info}><Text style={[styles.infoLabel, { color: colors.onSurfaceVariant }]}>{label}</Text><Text style={[styles.infoValue, { color: colors.onSurface }]}>{value}</Text></View> : null; }
function List({ label, values, colors }: any) { return <View style={styles.list}><Text style={[styles.infoLabel, { color: colors.onSurfaceVariant }]}>{label}</Text>{values.map((value: string, i: number) => <Text key={i} style={[styles.listItem, { color: colors.onSurface }]}>• {value}</Text>)}</View>; }
function Contact({ icon, label, onPress, colors }: any) { return <TouchableOpacity onPress={onPress} style={[styles.contact, { backgroundColor: colors.surfaceContainerHighest }]}><Ionicons name={icon} size={19} color={colors.primary} /><Text style={[styles.contactText, { color: colors.onSurface }]}>{label}</Text></TouchableOpacity>; }

const styles=StyleSheet.create({container:{flex:1},header:{flexDirection:'row',alignItems:'center',padding:24,gap:14},back:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},headerTitle:{...theme.typography.titleLg,fontWeight:'900'},content:{padding:24,paddingBottom:60,gap:8},hero:{alignItems:'center',padding:24,borderRadius:24},avatar:{width:72,height:72,borderRadius:24,alignItems:'center',justifyContent:'center',marginBottom:12},name:{...theme.typography.displayMd,fontSize:30,fontWeight:'900',textAlign:'center'},headline:{...theme.typography.labelLg,fontWeight:'900',marginTop:5,textAlign:'center'},verified:{flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:10,paddingVertical:6,borderRadius:12,marginTop:10},verifiedText:{...theme.typography.caption,fontWeight:'800'},section:{marginTop:18},sectionTitle:{...theme.typography.titleMd,fontWeight:'900',marginBottom:9},card:{padding:18,borderRadius:20,gap:13},body:{...theme.typography.bodyMd,lineHeight:21},info:{gap:2},infoLabel:{...theme.typography.caption,fontWeight:'700'},infoValue:{...theme.typography.bodyMd,lineHeight:20},list:{gap:4},listItem:{...theme.typography.bodyMd,lineHeight:21},contactGrid:{flexDirection:'row',flexWrap:'wrap',gap:9},contact:{paddingHorizontal:13,paddingVertical:11,borderRadius:14,flexDirection:'row',alignItems:'center',gap:7},contactText:{...theme.typography.labelMd,fontWeight:'800'},firmRow:{padding:14,borderRadius:15,flexDirection:'row',alignItems:'center',gap:10},firmText:{flex:1},firmName:{...theme.typography.bodyMd,fontWeight:'900'},enquiry:{minHeight:54,borderRadius:17,marginTop:22,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},enquiryText:{...theme.typography.labelLg,fontWeight:'900'}});